os: linux
language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: m/W1vxMrEAGXjbvvOCY2RBl91xW0AubcpSu1zDlechfglhzGkqfG5TNNbVyGBTPvl0QH8/EDyaF8kz5X/oT14VDfB9IEm/ZzqKHyrm3uTgacqc1xfzpFfHJNh+vV8AajujJDJBBOa91uDkMuVwgo/fqmXpOGW8CD+rQG6UEifoFefKrWaj43Ly8aSwMu8G6Z/sVe/+X7FzgwBIGkhMu9x9ZCMFIZQ3debAbXXzYdNKIG6wjVYZO1/sTKaauGPtcOeVAdZgdkkcTzCb2NI5RW+jT76bGlIBVyYIEzyphwJEl5Qp6WATupads/ujiEdV2fV5vcU/exX2CFmrCr/FvE3G/eP9Z+k/e+DXyqpbcMRFzjsGBzxndMvgZ/hZrpsdag1bOy6ZRO00bi9QeVpTD8UcO3aDT6n1rAc/qMk7J5NY9oKGzuJ+EODMX2z1PMYo/AN6Eq+D/XlTlcCqV79P/mrJNUbLs78UXEMgIUwVQSDn4Vt8wEZaPU1tnJapejobA/l0azYIF+9vO8BprbeP6UTpbP5N0mK7RPftRy/EUhZCh8wxMyKKw6S9dUvgMPkG2F0vm2A7RbtBFIK1gzgfHVltwCUUrRTvgYSJKJRXZ+yUfstlINhmcwm32UTE8uyJ6+aVd+03Cxaxp0cLifdPLSp4a4EE9OT6s0LB8XVc+DPnY=
addons:
  coverity_scan:
    project:
      name: IronPeak/TicTacToe
      description: TicTacToe application
    notification_email: hrafnorri1207@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master
before_install:
- pip install --user codecov
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: F6ZOm7pIIOJL7u4v5o9CPfUsyQNKh9jvybqlXR545Xu/IsdMqDPaPV1oUsxJOaD8WwS5raL5ucXwy8BsMlWB32JJxpUm6FRMuw5W15jkcm1nshUzVfFos8iVdxid2vOJPeNCQ93LS3HMVupYQraUZpr9wgDLdt1LSn0XLe0Eup90tEo2xeNJVTqIAfMN3LMHHOGVEegcGyZMner12FVjmz8vWGXgrr0fzKQdR2WuvX4AG0zk4LLak8XyjP2xwY7uFuXZudjMaMxPdtJ4we3uDXtyto3lz99XScP4j0yZ80r6W5ww/x9u4HzACSr71+RJMw54VVBcbghIPwMzb6WMrHesxxeguQAP2RDUhYNV4DDUGGPBzid4AhC1mpsvA6cvB1j7dfPoNMZ8AiSaLy57NNG/HqJjHyeYT3t+CJBssL8d7n95aV7J9k2yg08ulCppSuf7I7oxMbdip3pMOBAGfIQ9E4pKMqBh3SvNF37J92FBSMz4FtTBBQ5gcfJTGl9dnD2Hkpx1+aQBAIm+yMR/Igw5AoWEzW+t9EbezBz5MtauAKaC6+mAiK16DY7vJLpF7aCjgtNaajeO3EdVjwtry4RgUJRdE7DYCOsINv4Psk43XvFRdeS3CzeEhntXZq2i8WMejtQ3Nz14itaDQbwj2lfvi1VTjYW/tg+vPvltwTc=
  app: TicTacToe
  on:
    repo: IronPeak/TicTacToe
