/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gudni14' at '10/24/15 1:15 PM' with Gradle 2.8
 *
 * @author gudni14, @date 10/24/15 1:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
